
GREET_NEW_USERS: True
DISCORD_TOKEN: ''
DISCORD_SERVER: ''
OPENAI_HOST: 'localhost'
OPENAI_PORT: '8080'
OPENAI_ENDPOINT: 'v1'
STANDARD_GREETING: ''
CHROMA: True
GITHUB: True
CHANNEL_HISTORY: 10

SYSTEM_PROMPT: ''